const FETCH_SETTING_SUCCESS = "FETCH_SETTING_SUCCESS";
const  FETCH_LOADER = "FETCH_LOADER";
const FETCH_WINNERS_SUCCESS = "FETCH_WINNERS_SUCCESS";
const FETCH_ERROR = "FETCH_ERROR";
const SET_USER_NAME = "SET_USER_NAME";
const SET_USER_MODE = "SET_USER_MODE";
const SET_USER_NAME_ERROR = "SET_USER_NAME_ERROR";
const SET_USER_MODE_ERROR = "SET_USER_MODE_ERROR";
const START_USER_GAME = "START_USER_GAME";
const ADD_ELEMENT_FIELD = 'ADD_ELEMENT_FIELD';
const CHANGE_ELEMENT_STATUS = "CHANGE_ELEMENT_STATUS";
const END_USER_GAME = "END_USER_GAME";



export {
  FETCH_SETTING_SUCCESS,
  FETCH_WINNERS_SUCCESS,
  FETCH_LOADER,
  FETCH_ERROR,
  SET_USER_NAME,
  SET_USER_MODE,
  SET_USER_NAME_ERROR,
  SET_USER_MODE_ERROR,
  START_USER_GAME,
  ADD_ELEMENT_FIELD,
  CHANGE_ELEMENT_STATUS,
  END_USER_GAME
};